# id, slug, title, description, group
META = [
(1,"pdnca-2004-sections-1-23","Punjab Destitute & Neglected Children Act 2004: Sections 1-23","Short title, definitions, Child Protection & Welfare Bureau, Board, Director General, Courts","Child Protection Act"),
(2,"pdnca-2004-sections-24-51","Punjab Destitute & Neglected Children Act 2004: Sections 24-51","Rescue, custody, offences and penalties, fund, miscellaneous provisions","Child Protection Act"),
(3,"pdnca-2004-numbers-one-liners","Punjab Child Protection Act 2004: Numbers & One-liners","Parts, periods, amounts, ages and who-is-who drill","Child Protection Act"),
(4,"uncrc-child-rights","UNCRC & International Child Rights","Convention articles, ILO standards, international days and bodies","Child Rights & Law"),
(5,"pakistan-child-laws","Pakistan Child-Related Laws","Constitution, JJSO 2000, PPC, family laws, writs and child protection statutes","Child Rights & Law"),
(6,"child-protection-practice","Child Protection Practice & Procedure","CPO role, diversion, consent, ILO conventions and rehabilitation","Child Rights & Law"),
(7,"child-protection-scenarios","Child Protection Scenarios & Mixed Mock","Situation-based questions on casework, child labour and first response","Child Rights & Law"),
(8,"child-protection-law-concepts","Child Protection Law & Concepts","The Bureau, Zainab Alert Act, prevention, probation and children at risk","Child Rights & Law"),
(9,"social-work-1","Social Work I","Casework, group work, community organisation and models","Social Sciences"),
(10,"social-work-2-counselling","Social Work II: Counselling, Welfare & Research","Counselling, NGOs, welfare institutions and research basics","Social Sciences"),
(11,"psychology-child-development","Psychology & Child Development","Piaget, Erikson, Freud, learning, trauma and behaviour","Social Sciences"),
(12,"sociology","Sociology","Family, culture, deviance, stratification and theorists","Social Sciences"),
(13,"criminology-juvenile-delinquency","Criminology & Juvenile Delinquency","Crime theories, juvenile justice, probation and prevention","Social Sciences"),
(14,"pakistan-studies-basics","Pakistan Studies: Pakistan Movement & Basics","Lahore Resolution, 3 June Plan, heritage sites and national symbols","Pakistan Studies"),
(15,"constitution-governance","Constitution, Governance & Public Administration","Articles, Parliament, courts, NAB and administration","Pakistan Studies"),
(16,"pakistan-history-firsts","Pakistan: History, Political Firsts & Amendments","Firsts, leaders, treaties, wars and constitutional milestones","Pakistan Studies"),
(17,"pakistan-geography-economy","Pakistan: Geography, Resources & Economy","Rivers, mountains, dams, minerals, crops, cities and CPEC","Pakistan Studies"),
(18,"pakistan-culture-personalities","Pakistan: Culture, Personalities & Landmarks","Festivals, heroes, sports, awards and monuments","Pakistan Studies"),
(19,"islamic-studies-1","Islamic Studies I","Quran, calendar, Khulafa, Sunnah and pillars of Islam","Islamic Studies"),
(20,"islamic-studies-2","Islamic Studies II: Hadith, History & Fiqh","Battles, Companions, hadith collections, prophets and fiqh","Islamic Studies"),
(21,"current-affairs-pakistan-1","Current Affairs Pakistan I","Elections, 2025 events, floods, Kashmir and Kartarpur","Current Affairs"),
(22,"current-affairs-pakistan-2","Current Affairs Pakistan II","Institutions, constitution in practice, economy and government","Current Affairs"),
(23,"world-affairs-gk-1","World Affairs & General Knowledge I","UN, OIC, deserts, capitals and international days","Current Affairs"),
(24,"current-affairs-world-2","Current Affairs World II","Organisations, treaties, summits and international days","Current Affairs"),
(25,"world-geography-capitals","World Geography I: Continents & Capitals","Continents, oceans, countries and capitals","GK & Geography"),
(26,"world-geography-rivers-straits","World Geography II: Rivers, Lakes, Straits & Nicknames","Rivers, lakes, straits, mountains, deserts and city nicknames","GK & Geography"),
(27,"gk-inventions-books","General Knowledge I: Inventions, Books & Abbreviations","Inventors, discoveries, authors and common abbreviations","GK & Geography"),
(28,"gk-sports-awards","General Knowledge II: Sports, Awards & Landmarks","Sports, Nobel and other awards, currencies and wonders","GK & Geography"),
(29,"everyday-science-1","Everyday Science I","Physics, chemistry, biology and IT basics","Everyday Science"),
(30,"everyday-science-physics-chemistry","Everyday Science II: Physics & Chemistry","Units, light, electricity, elements, acids and materials","Everyday Science"),
(31,"everyday-science-biology-health","Everyday Science III: Biology, Health & Environment","Cells, body systems, vitamins, diseases and pollution","Everyday Science"),
(32,"computer-fundamentals-windows","Computer Skills I: Fundamentals, Hardware & Windows","Hardware, software, memory, number systems and shortcuts","Computer & IT"),
(33,"ms-office-internet","Computer Skills II: MS Office, Internet & Cyber Safety","Word, Excel, PowerPoint, internet, email and phishing","Computer & IT"),
(34,"english-1","English I: Synonyms, Antonyms & Idioms","Vocabulary, idioms and grammar basics","English"),
(35,"english-antonyms-one-word-idioms","English II: Antonyms, One-word Substitution & Idioms","Antonyms, one-word substitutions, idioms and phrases","English"),
(36,"english-grammar-voice-narration","English III: Grammar, Voice & Narration","Tenses, voice, narration, prepositions and articles","English"),
(37,"english-spelling-error-spotting","English IV: Spelling, Error Spotting & Usage","Spelling, sentence correction, confused words and punctuation","English"),
(38,"urdu-1","Urdu I / اردو","Literature, grammar, proverbs and poets","Urdu"),
(39,"urdu-literature","Urdu II / اردو: ادب","Poets, authors, books and literary forms","Urdu"),
(40,"urdu-grammar-vocabulary","Urdu III / اردو: قواعد و محاورات","Grammar, synonyms, antonyms, plurals and idioms","Urdu"),
(41,"maths-reasoning-1","Basic Maths & Reasoning I","Series, average, LCM, analogies and clock problems","Maths & Reasoning"),
(42,"maths-reasoning-2","Basic Maths & Reasoning II","Percentages, ratio, interest, time-work and reasoning","Maths & Reasoning"),
]
